### PR TITLE
Update papers; add details about issues, PRs, discussions; add favicon

### PR DESCRIPTION
**Pull request by felker**
Related to #503

### CODE REVIEW

**Comment by felker** [comment]
I am fine keeping Jiang et al (2014) in the list of code papers as a one time exception for the rule that "the paper at least must mention Athena++ by name once" since I dont think the Athena (C) version with radiation was ever made public?

**Comment by pgrete** [comment]
Is it worth mentioning K-Athena and Parthenon as "forked codes"?

**Comment by felker** [comment]
I think that makes sense

**Comment by pgrete** [comment]
In that case:

```html

  <li><a href="https://ui.adsabs.harvard.edu/abs/2021ITPDS..32...85G/abstract">K-Athena: a performance portable structured grid finite volume magnetohydrodynamics code</a>, Grete, P. and Glines, F. W. and O'Shea, B. W. 2021, IEEE Transactions on Parallel and Distributed Systems, Vol. 32, Issue 1, pp. 85-907
  </li>


  <li><a href="https://ui.adsabs.harvard.edu/abs/2022arXiv220212309G/abstract">Parthenon -- a performance portable block-structured adaptive mesh refinement framework </a>,Philipp Grete and Joshua C Dolence and Jonah M Miller and Joshua Brown and Ben Ryan and Andrew Gaspar and Forrest Glines and Sriram Swaminarayan and Jonas Lippuner and Clell J Solomon and Galen Shipman and Christoph Junghans and Daniel Holladay and James M Stone and Luke F Roberts 2022, The International Journal of High Performance Computing Applications
  </li>
  <!-- https://journals.sagepub.com/doi/full/10.1177/10943420221143775 -->

```

**Comment by tomidakn** [comment]
Looks good to me. If there is no objection / addition, I think we can update the webpage.

**Pull request merged**
