### PR TITLE
Add explicit cast for safety

### PR DESCRIPTION
**Pull request by felker**
See #518

### CODE REVIEW

**Review by tomidakn — APPROVED** [review]

**Comment by felker** [comment]
@changgoo what are the details of the failed build?

**Comment by changgoo** [comment]
I thought that we are going to work on #518 to pass the regression tests on Jenkins.

You may apply this commit first: 595bf5396bfb2f1a2d71658e33d4ec0cb48c50e4

**Comment by changgoo** [comment]
Since there will be many such fixes, which one is better? many PRs vs. one PR with many commits?

**Comment by felker** [comment]
Good point @changgoo; I will close this and cherry pick the commit on your PR

**Pull request closed without merging**
